# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:  
  - build  
  - test  
  - deploy  
  
variables:  
  DOTNET_CLI_TELEMETRY_OPTOUT: 1  
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1  
  
# 定义构建任务  
build-job:  
  stage: build  
  tags:
    - dev
  script:  
    - cd /home
    - sudo rm -rf FinanceTracker
    - sudo git clone -b dev https://gitlab.cyanbin.com/cyanbin/FinanceTracker.git
    - cd FinanceTracker/src
    - docker build -f FinanceTracker.Service/Dockerfile -t FinanceTracker.Service .
  only:  
    - merge_requests  
    - main  
    - dev
  
# 定义测试任务  
test-job:  
  stage: test  
  image: mcr.microsoft.com/dotnet/core/sdk:3.1  
  needs:  
    - job: build-job # 依赖build-job的输出  
  script:  
    - dotnet test # 运行测试  
  only:  
    - merge_requests  
    - main  
  
# 定义部署任务（这里以部署到Docker镜像为例）  
deploy-job:  
  stage: deploy  
  image: docker:latest  
  services:  
    - docker:dind # 使用Docker in Docker服务  
  variables:  
    DOCKER_DRIVER: overlay2  
    DOCKER_HOST: tcp://docker:2375  
    DOCKER_TLS_CERTDIR: ""  
  needs:  
    - job: test-job # 依赖test-job的完成  
  script:  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY # 登录到GitLab的容器仓库  
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG . # 构建Docker镜像  
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG # 推送Docker镜像到仓库  
  only:  
    - main # 只在main分支上部署  
  
# 在所有阶段完成后执行  
post-deploy:  
  stage: deploy  
  script:  
    - echo "Deployment finished!"  
  when: always # 无论成功还是失败都执行  
  only:  
    - main
